### ISSUE TITLE
Intermittent error message: java.lang.NullPointerException

### ISSUE THREAD

**Issue by hubgitti** [JOSM/austriaaddresshelper#7]
Hi,

from time time (rarely) I get the following error message:
Austria Address Helper An unexpected exception occurred: java.lang.NullPointerException

In that case, the tool fails to work.

Is it possible to fix that behaviour or turn it into a more meaningful error message? Do you need  any further information to debug that issue?

hubgitti

**Comment by thomaskonrad** [comment]
Hi hubgitti,

thank you for reporting this. Would you be so kind as to start JOSM from the command line (`java -jar josm.jar`) and copy the whole stack trace from the console output the next time it happens? That would help me.

Let me know if you need support with this.

Thank you
Thomas

**Comment by hubgitti** [comment]
Hi, I used the following command, used the address helper and got  the  error again:
java -jar josm-tested.jar > tmp/JosmOutput.txt 2>&1

The output is:
2018-03-09 10:52:24.001 INFORMATION: Protokollierungsgrad ist bei INFORMATION (INFO, 800)
2018-03-09 10:52:25.699 INFO: loading plugin 'log4j' (version 32699)
2018-03-09 10:52:28.632 INFO: Update imagery 'OpenStreetMap (Standard Black & White)'
2018-03-09 10:52:30.072 INFO: Defaults for imagery.generic.default_autozoom differ:  != true
2018-03-09 10:52:30.073 INFO: Defaults for imagery.generic.default_autoload differ:  != true
2018-03-09 10:52:30.073 INFO: Defaults for imagery.generic.default_showerrors differ:  != true
2018-03-09 10:52:30.137 INFO: Could not load tool definition dialogs/validator
2018-03-09 10:52:30.137 INFO: Could not load tool definition dialogs/commandstack
2018-03-09 10:52:30.184 INFO: loading plugin 'reverter' (version 34036)
2018-03-09 10:52:30.230 INFO: RemoteControl: adding command "revert_changeset" (handled by RevertChangesetHandler)
2018-03-09 10:52:30.231 INFO: loading plugin 'apache-commons' (version 33668)
2018-03-09 10:52:30.234 INFO: loading plugin 'reltoolbox' (version 33708)
2018-03-09 10:52:30.249 INFO: loading plugin 'jts' (version 32699)
2018-03-09 10:52:30.250 INFO: loading plugin 'ejml' (version 32680)
2018-03-09 10:52:30.251 INFO: loading plugin 'apache-http' (version 32699)
2018-03-09 10:52:30.254 INFO: loading plugin 'geotools' (version 33958)
2018-03-09 10:52:30.269 WARNING: No configuration settings found.  Using hardcoded default values for all pools.
2018-03-09 10:52:31.078 INFO: Warp/affine reduction enabled: true
2018-03-09 10:52:32.495 INFO: loading plugin 'utilsplugin2' (version 33991)
2018-03-09 10:52:32.644 INFO: loading plugin 'HouseNumberTaggingTool' (version 34074)
2018-03-09 10:52:32.656 INFO: loading plugin 'opendata' (version 34072)
2018-03-09 10:52:32.686 INFO: loading plugin 'measurement' (version 33760)
2018-03-09 10:52:32.688 INFO: loading plugin 'pbf' (version 33568)
2018-03-09 10:52:32.710 INFO: loading plugin 'ImportImagePlugin' (version 33563)
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
2018-03-09 10:52:34.833 INFO: loading plugin 'OpeningHoursEditor' (version 33876)
2018-03-09 10:52:34.851 INFO: loading plugin 'areaselector' (version 336)
2018-03-09 10:52:34.944 INFO: loading plugin 'undelete' (version 33980)
2018-03-09 10:52:34.950 INFO: loading plugin 'buildings_tools' (version 34040)
2018-03-09 10:52:34.954 INFO: Reassigning shortcut 'edit:buildingsdialog' from null to 576 because of conflict with Ctrl+Alt+B
2018-03-09 10:52:34.954 INFO: Silent shortcut conflict: 'edit:buildingsdialog' moved by 'tools:tagbuilding' to 'Alt+Shift+F1'.
2018-03-09 10:52:34.983 INFO: loading plugin 'terracer' (version 33839)
2018-03-09 10:52:35.004 INFO: loading plugin 'turnrestrictions' (version 33780)
2018-03-09 10:52:35.006 INFO: loading plugin 'austriaaddresshelper' (version 1511306130)
2018-03-09 10:52:35.022 INFO: loading plugin 'PicLayer' (version 34021)
2018-03-09 10:52:35.036 INFO: loading plugin 'contourmerge' (version 1032)
2018-03-09 10:52:35.051 INFO: Could not load tool definition dialogs/validator
2018-03-09 10:52:35.051 INFO: Could not load tool definition dialogs/commandstack
2018-03-09 10:52:35.211 INFO: RemoteControl::Accepting remote connections on /127.0.0.1:8111
2018-03-09 10:52:35.218 INFO: RemoteControl::Accepting remote connections on /0:0:0:0:0:0:0:1:8111
2018-03-09 10:52:35.240 INFO: RemoteControl::Accepting secure remote connections on /127.0.0.1:8112
2018-03-09 10:52:35.242 INFO: RemoteControl::Accepting secure remote connections on /0:0:0:0:0:0:0:1:8112
2018-03-09 10:52:35.247 INFO: Message notifier active (checks every 5 minutes)
2018-03-09 10:52:35.679 INFO: GET https://api.openstreetmap.org/api/0.6/user/details (get number of unread messages) -> 200 (1.09 kB)
2018-03-09 10:52:38.980 INFO: GET https://a.tile.openstreetmap.org/13/4426/2876.png -> 200 (10.6 kB)
2018-03-09 10:52:39.049 INFO: GET https://b.tile.openstreetmap.org/13/4428/2876.png -> 200 (13.7 kB)
2018-03-09 10:52:39.049 INFO: GET https://c.tile.openstreetmap.org/13/4427/2876.png -> 200 (7.53 kB)
2018-03-09 10:52:39.058 INFO: GET https://c.tile.openstreetmap.org/13/4427/2875.png -> 200 (15.6 kB)
2018-03-09 10:52:39.064 INFO: GET https://c.tile.openstreetmap.org/13/4429/2875.png -> 200 (26.1 kB)
2018-03-09 10:52:39.075 INFO: GET https://a.tile.openstreetmap.org/13/4428/2874.png -> 200 (21.8 kB)
2018-03-09 10:52:39.077 INFO: GET https://a.tile.openstreetmap.org/13/4430/2875.png -> 200 (20.3 kB)
2018-03-09 10:52:39.077 INFO: GET https://a.tile.openstreetmap.org/13/4427/2874.png -> 200 (21.5 kB)
2018-03-09 10:52:39.083 INFO: GET https://c.tile.openstreetmap.org/13/4430/2874.png -> 200 (21.8 kB)
2018-03-09 10:52:39.088 INFO: GET https://b.tile.openstreetmap.org/13/4427/2873.png -> 200 (20.4 kB)
2018-03-09 10:52:39.093 INFO: GET https://b.tile.openstreetmap.org/13/4428/2875.png -> 200 (21.4 kB)
2018-03-09 10:52:39.097 INFO: GET https://b.tile.openstreetmap.org/13/4429/2874.png -> 200 (23.1 kB)
2018-03-09 10:52:39.104 INFO: GET https://a.tile.openstreetmap.org/13/4429/2876.png -> 200 (16.3 kB)
2018-03-09 10:52:39.136 INFO: GET https://b.tile.openstreetmap.org/13/4425/2874.png -> 200 (16.7 kB)
2018-03-09 10:52:39.141 INFO: GET https://c.tile.openstreetmap.org/13/4427/2873.png -> 200 (20.4 kB)
2018-03-09 10:52:39.143 INFO: GET https://a.tile.openstreetmap.org/13/4429/2873.png -> 200 (19.4 kB)
2018-03-09 10:52:39.339 INFO: GET https://b.tile.openstreetmap.org/13/4426/2875.png -> 200 (8.57 kB)
2018-03-09 10:52:39.605 INFO: GET https://c.tile.openstreetmap.org/13/4429/2874.png -> 200 (23.1 kB)
2018-03-09 10:52:39.635 INFO: GET https://c.tile.openstreetmap.org/13/4425/2876.png -> 200 (12.9 kB)
2018-03-09 10:52:39.678 INFO: GET https://a.tile.openstreetmap.org/13/4426/2873.png -> 200 (16.8 kB)
2018-03-09 10:52:39.687 INFO: GET https://a.tile.openstreetmap.org/13/4425/2875.png -> 200 (13.6 kB)
2018-03-09 10:52:39.705 INFO: GET https://b.tile.openstreetmap.org/13/4426/2873.png -> 200 (16.8 kB)
2018-03-09 10:52:39.714 INFO: GET https://b.tile.openstreetmap.org/13/4428/2874.png -> 200 (21.6 kB)
2018-03-09 10:52:39.747 INFO: GET https://c.tile.openstreetmap.org/13/4430/2873.png -> 200 (18.8 kB)
2018-03-09 10:52:39.759 INFO: GET https://c.tile.openstreetmap.org/13/4426/2873.png -> 200 (16.8 kB)
2018-03-09 10:52:39.777 INFO: GET https://b.tile.openstreetmap.org/13/4426/2874.png -> 200 (17.8 kB)
2018-03-09 10:52:39.812 INFO: GET https://a.tile.openstreetmap.org/13/4428/2873.png -> 200 (19.5 kB)
2018-03-09 10:52:39.828 INFO: GET https://c.tile.openstreetmap.org/13/4426/2874.png -> 200 (17.8 kB)
2018-03-09 10:52:39.832 INFO: GET https://b.tile.openstreetmap.org/13/4425/2875.png -> 200 (13.6 kB)
2018-03-09 10:52:39.847 INFO: GET https://a.tile.openstreetmap.org/13/4430/2873.png -> 200 (18.8 kB)
2018-03-09 10:52:39.851 INFO: GET https://a.tile.openstreetmap.org/13/4426/2874.png -> 200 (17.8 kB)
2018-03-09 10:52:39.856 INFO: GET https://b.tile.openstreetmap.org/13/4428/2873.png -> 200 (19.5 kB)
2018-03-09 10:52:40.313 INFO: GET https://b.tile.openstreetmap.org/13/4425/2873.png -> 200 (15.8 kB)
2018-03-09 10:52:40.315 INFO: GET https://a.tile.openstreetmap.org/13/4425/2873.png -> 200 (15.8 kB)
2018-03-09 10:52:40.318 INFO: GET https://c.tile.openstreetmap.org/13/4425/2873.png -> 200 (15.8 kB)
2018-03-09 10:52:40.732 INFO: GET https://c.tile.openstreetmap.org/13/4428/2873.png -> 200 (19.5 kB)
2018-03-09 10:52:41.536 INFO: GET https://b.tile.openstreetmap.org/14/8853/5749.png -> 200 (12.1 kB)
2018-03-09 10:52:41.538 INFO: GET https://a.tile.openstreetmap.org/14/8853/5750.png -> 200 (5.12 kB)
2018-03-09 10:52:41.542 INFO: GET https://c.tile.openstreetmap.org/14/8853/5751.png -> 200 (7.23 kB)
2018-03-09 10:52:41.563 INFO: GET https://a.tile.openstreetmap.org/14/8855/5748.png -> 200 (19.2 kB)
2018-03-09 10:52:41.564 INFO: GET https://a.tile.openstreetmap.org/14/8854/5749.png -> 200 (11.3 kB)
2018-03-09 10:52:41.566 INFO: JCS - Host: https://b.tile.openstreetmap.org found not to return 304 codes for If-Modified-Since or If-None-Match headers
2018-03-09 10:52:41.575 INFO: GET https://c.tile.openstreetmap.org/14/8857/5748.png -> 200 (16.1 kB)
2018-03-09 10:52:41.580 INFO: GET https://a.tile.openstreetmap.org/14/8858/5748.png -> 200 (14.0 kB)
2018-03-09 10:52:41.599 INFO: GET https://c.tile.openstreetmap.org/14/8854/5748.png -> 200 (15.2 kB)
2018-03-09 10:52:41.627 INFO: GET https://b.tile.openstreetmap.org/14/8854/5748.png -> 200 (15.2 kB)
2018-03-09 10:52:41.629 INFO: GET https://c.tile.openstreetmap.org/14/8858/5748.png -> 200 (14.0 kB)
2018-03-09 10:52:41.636 INFO: GET https://c.tile.openstreetmap.org/14/8853/5748.png -> 200 (12.9 kB)
2018-03-09 10:52:41.669 INFO: GET https://b.tile.openstreetmap.org/14/8854/5749.png -> 200 (11.3 kB)
2018-03-09 10:52:41.669 INFO: JCS - Host: https://c.tile.openstreetmap.org found not to return 304 codes for If-Modified-Since or If-None-Match headers
2018-03-09 10:52:41.681 INFO: GET https://a.tile.openstreetmap.org/14/8854/5748.png -> 200 (15.2 kB)
2018-03-09 10:52:41.691 INFO: GET https://b.tile.openstreetmap.org/14/8853/5748.png -> 200 (12.9 kB)
2018-03-09 10:52:41.699 INFO: GET https://a.tile.openstreetmap.org/14/8853/5748.png -> 200 (12.9 kB)
2018-03-09 10:52:41.711 INFO: GET https://c.tile.openstreetmap.org/14/8855/5748.png -> 200 (19.2 kB)
2018-03-09 10:52:41.714 INFO: GET https://a.tile.openstreetmap.org/14/8856/5748.png -> 200 (15.0 kB)
2018-03-09 10:52:41.714 INFO: GET https://b.tile.openstreetmap.org/14/8856/5748.png -> 200 (15.0 kB)
2018-03-09 10:52:41.721 INFO: GET https://c.tile.openstreetmap.org/14/8856/5748.png -> 200 (15.0 kB)
2018-03-09 10:52:41.729 INFO: GET https://b.tile.openstreetmap.org/14/8857/5748.png -> 200 (16.1 kB)
2018-03-09 10:52:41.751 INFO: GET https://b.tile.openstreetmap.org/14/8855/5748.png -> 200 (19.2 kB)
2018-03-09 10:52:41.933 INFO: GET https://a.tile.openstreetmap.org/14/8857/5748.png -> 200 (16.1 kB)
2018-03-09 10:52:43.126 INFO: GET https://b.tile.openstreetmap.org/14/8858/5749.png -> 200 (9.79 kB)
2018-03-09 10:52:43.127 INFO: GET https://a.tile.openstreetmap.org/14/8858/5749.png -> 200 (9.79 kB)
2018-03-09 10:52:43.127 INFO: GET https://c.tile.openstreetmap.org/14/8858/5749.png -> 200 (9.79 kB)
2018-03-09 10:52:43.638 INFO: GET https://a.tile.openstreetmap.org/15/17715/11498.png -> 200 (11.9 kB)
2018-03-09 10:52:43.760 INFO: GET https://c.tile.openstreetmap.org/15/17715/11500.png -> 200 (13.2 kB)
2018-03-09 10:52:43.844 INFO: GET https://b.tile.openstreetmap.org/15/17715/11499.png -> 200 (14.1 kB)
2018-03-09 10:52:44.213 INFO: GET https://b.tile.openstreetmap.org/13/4430/2873.png -> 200 (18.7 kB)
2018-03-09 10:52:45.217 INFO: GET https://api.openstreetmap.org/api/0.6/map?bbox=14.5941353,47.1929787,14.5979118,47.1958366 -> 200
2018-03-09 10:52:46.276 INFO: Reassigning shortcut 'reltoolbox:addremove' from null to 576 because of conflict with Equals
2018-03-09 10:52:46.276 INFO: Silent shortcut conflict: 'reltoolbox:addremove' moved by 'view:zoominter' to 'Alt+Shift+F2'.
2018-03-09 10:52:46.296 INFO: Reassigning shortcut 'reltoolbox:multipolygon' from null to 576 because of conflict with Ctrl+Alt+A
2018-03-09 10:52:46.296 INFO: Silent shortcut conflict: 'reltoolbox:multipolygon' moved by 'tools:areaselector' to 'Alt+Shift+F3'.
2018-03-09 10:52:49.897 WARNING: Exception on Toolkit thread
java.lang.ArrayIndexOutOfBoundsException: 85
	at sun.awt.X11.XEvent.getFieldsAsString(XEvent.java:86)
	at sun.awt.X11.XWrapperBase.toString(XWrapperBase.java:37)
	at sun.awt.X11.XEvent.toString(XEvent.java:8)
	at java.lang.String.valueOf(String.java:2994)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.doLog(PlatformLogger.java:626)
	at sun.util.logging.PlatformLogger.finer(PlatformLogger.java:387)
	at sun.awt.X11.XToolkit.run(XToolkit.java:586)
	at sun.awt.X11.XToolkit.run(XToolkit.java:532)
	at java.lang.Thread.run(Thread.java:748)

2018-03-09 10:52:50.132 INFO: GET https://bev-reverse-geocoder.thomaskonrad.at/reverse-geocode/json?lat=47.193731&lon=14.5963182&distance=30&limit=1&epsg=4326 (JOSM Plugin Austria Address Helper) -> 500
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.austriaaddresshelper.AustriaAddressHelperAction.loadAddress(AustriaAddressHelperAction.java:109)
	at org.openstreetmap.josm.plugins.austriaaddresshelper.AustriaAddressHelperAction.actionPerformed(AustriaAddressHelperAction.java:73)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:263)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-03-09 10:52:55.503 WARNING: Exception on Toolkit thread
java.lang.ArrayIndexOutOfBoundsException: 85
	at sun.awt.X11.XEvent.getFieldsAsString(XEvent.java:86)
	at sun.awt.X11.XWrapperBase.toString(XWrapperBase.java:37)
	at sun.awt.X11.XEvent.toString(XEvent.java:8)
	at java.lang.String.valueOf(String.java:2994)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.doLog(PlatformLogger.java:626)
	at sun.util.logging.PlatformLogger.finer(PlatformLogger.java:387)
	at sun.awt.X11.XToolkit.run(XToolkit.java:586)
	at sun.awt.X11.XToolkit.run(XToolkit.java:532)
	at java.lang.Thread.run(Thread.java:748)

**Comment by thomaskonrad** [comment]
Thanks, that helped me. It was a problem on the server, it‘s fixed now.

**Comment by hubgitti** [comment]
Juchu! ;-)
